# This is a basic workflow to help you get started with Actions

name: CI Testing

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    timeout-minutes: 20
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #    with:
        # submodules: recursive

      # Runs a single command using the runners shell
      - name: Compiling repo
        run: |
          make clean
          make


  test:
    runs-on: self-hosted

    timeout-minutes: 20

    needs: build

    steps:
   
      # Baseline implements a 16 set direct mapped cache 
      - name: Checking 2KB cache, 128B block, 1-way
        run: |
          ./cachesim -i traces/gcc-10K.memtrace -c 2KB -b 128B -w 1 &> output
          diff -y output .github/test/10K-2KB-128B-1
        if: always()

      - name: Checking 2KB cache, 128B block, 1-way
        run: |
          ./cachesim -i traces/gcc-650K.memtrace -c 2KB -b 128B -w 1 &> output
          diff -y output .github/test/650K-2KB-128B-1
        if: always()

      # Testing implementations  
      - name: Checking 512KB cache, 16B block, 4-way
        run: |
          ./cachesim -i traces/gcc-10K.memtrace -c 512KB -b 16B -w 4 &> output
          diff -y output .github/test/10K-512KB-16B-4
        if: always()

      - name: Checking 512KB cache, 16B block, 2-way
        run: |
          ./cachesim -i traces/gcc-10K.memtrace -c 512KB -b 16B -w 2 &> output
          diff -y output .github/test/10K-512KB-16B-2
        if: always()

      - name: Checking 512KB cache, 16B block, Direct mapped
        run: |
          ./cachesim -i traces/gcc-10K.memtrace -c 512KB -b 16B -w 1 &> output
          diff -y output .github/test/10K-512KB-16B-1
        if: always()

      - name: Checking 512KB cache, 16B block, Fully associative
        run: |
          ./cachesim -i traces/gcc-10K.memtrace -c 512KB -b 16B -w 32768 &> output
          diff -y output .github/test/10K-512KB-16B-0
        if: always()

      - name: Checking 256KB cache, 16B block, 4-way 
        run: |
          ./cachesim -i traces/gcc-650K.memtrace -c 256KB -b 16B -w 4 &> output
          diff -y output .github/test/650K-256KB-16B-4
        if: always()

      - name: Checking 256KB cache, 64B block, 4-way
        run: |
          ./cachesim -i traces/gcc-650K.memtrace -c 256KB -b 64B -w 4 &> output
          diff -y output .github/test/650K-256KB-64B-4
        if: always()

      - name: Checking 512KB cache, 16B block, Fully associative
        run: |
          ./cachesim -i traces/gcc-650K.memtrace -c 512KB -b 16B -w 32768 &> output
          diff -y output .github/test/650K-512KB-16B-0
        if: always()

      - name: Checking 512KB cache, 16B block, Direct mapped
        run: |
          ./cachesim -i traces/gcc-650K.memtrace -c 512KB -b 16B -w 1 &> output
          diff -y output .github/test/650K-512KB-16B-1
        if: always()

      - name: Checking 512KB cache, 16B block, 2-way
        run: |
          ./cachesim -i traces/gcc-650K.memtrace -c 512KB -b 16B -w 2 &> output
          diff -y output .github/test/650K-512KB-16B-2
        if: always()

      - name: Checking 512KB cache, 16B block, 4-way
        run: |
          ./cachesim -i traces/gcc-650K.memtrace -c 512KB -b 16B -w 4 &> output
          diff -y output .github/test/650K-512KB-16B-4
        if: always()

      - name: Checking 64KB cache, 32B block, 2-way
        run: |
          ./cachesim -i traces/gcc-650K.memtrace -c 64KB -b 32B -w 2 &> output
          diff -y output .github/test/650K-64KB-32B-2
        if: always()

  cleanup:
    
    runs-on: self-hosted
    if: always()
    needs: [build,test]
    steps:
      - name: Clean up
        run: echo "Cleaning up previous run"; rm -rf "${{ github.workspace }}";
